version: '3'

services:
  db:
    container_name: pokedex-db
    image: mongo:7.0
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - mongo-db:/data/db
      - mongo-db-config:/data/configdb

volumes:
  mongo-db:
    external: false
  mongo-db-config:
    external: false
